import image1Url from '../assets/images/image1.png';
import image2Url from '../assets/images/image2.png';
import image3Url from '../assets/images/image3.png';
import bottleImgUrl from '../assets/images/bottle.svg';
import boxImgUrl from '../assets/images/box.svg';

import { CardTypeProps } from '../components/card/Card';

export const goodsData:Array<CardTypeProps> = [
  {
    imgUrl: image1Url,
    title: 'AOS',
    description: 'средство для мытья посуды Crystal',
    quantity: '450 мл',
    quantityImg:bottleImgUrl,
    barcode: '4604049097548',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
  },
  {
    imgUrl: image2Url,
    title: 'ARIEL',
    description: 'Автомат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник',
    quantity: '15X28.8 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097548',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
  },
  {
    imgUrl: image3Url,
    title: 'BIMAX',
    description: 'Порошок стиральный Автомат 100 пятен COMPACT',
    quantity: '1500 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097548',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
  },
  {
    imgUrl: image1Url,
    title: 'AOS',
    description: 'средство для мытья посуды Crystal',
    quantity: '450 мл',
    quantityImg:bottleImgUrl,
    barcode: '4604049097548',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
  },
  {
    imgUrl: image2Url,
    title: 'ARIEL',
    description: 'Автомат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник',
    quantity: '15X28.8 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097548',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
  },
  {
    imgUrl: image3Url,
    title: 'BIMAX',
    description: 'Порошок стиральный Автомат 100 пятен COMPACT',
    quantity: '1500 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097548',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
  },
  {
    imgUrl: image1Url,
    title: 'AOS',
    description: 'средство для мытья посуды Crystal',
    quantity: '450 мл',
    quantityImg:bottleImgUrl,
    barcode: '4604049097548',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
  },
  {
    imgUrl: image2Url,
    title: 'ARIEL',
    description: 'Автомат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник',
    quantity: '15X28.8 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097548',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
  },
  {
    imgUrl: image3Url,
    title: 'BIMAX',
    description: 'Порошок стиральный Автомат 100 пятен COMPACT',
    quantity: '1500 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097548',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
  },
  {
    imgUrl: image1Url,
    title: 'AOS',
    description: 'средство для мытья посуды Crystal',
    quantity: '450 мл',
    quantityImg:bottleImgUrl,
    barcode: '4604049097548',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
  },
  {
    imgUrl: image2Url,
    title: 'ARIEL',
    description: 'Автомат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник',
    quantity: '15X28.8 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097548',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
  },
  {
    imgUrl: image3Url,
    title: 'BIMAX',
    description: 'Порошок стиральный Автомат 100 пятен COMPACT',
    quantity: '1500 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097548',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
  },
  {
    imgUrl: image1Url,
    title: 'AOS',
    description: 'средство для мытья посуды Crystal',
    quantity: '450 мл',
    quantityImg:bottleImgUrl,
    barcode: '4604049097548',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
  },
  {
    imgUrl: image2Url,
    title: 'ARIEL',
    description: 'Автомат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник',
    quantity: '15X28.8 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097548',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
  },
  {
    imgUrl: image3Url,
    title: 'BIMAX',
    description: 'Порошок стиральный Автомат 100 пятен COMPACT',
    quantity: '1500 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097548',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
  },
  {
    imgUrl: image1Url,
    title: 'AOS',
    description: 'средство для мытья посуды Crystal',
    quantity: '450 мл',
    quantityImg:bottleImgUrl,
    barcode: '4604049097548',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
  },
  {
    imgUrl: image2Url,
    title: 'ARIEL',
    description: 'Автомат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник',
    quantity: '15X28.8 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097548',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
  },
  {
    imgUrl: image3Url,
    title: 'BIMAX',
    description: 'Порошок стиральный Автомат 100 пятен COMPACT',
    quantity: '1500 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097548',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
  },
]