import image1Url from '../assets/images/image1.png';
import image2Url from '../assets/images/image2.png';
import image3Url from '../assets/images/image3.png';
import bottleImgUrl from '../assets/images/bottle.svg';
import boxImgUrl from '../assets/images/box.svg';

import { CardTypeProps } from '../components/card/Card';

const goodsData:Array<CardTypeProps> = [
  {
    imgUrl: image1Url,
    title: 'AOS',
    description: 'средство для мытья посуды Crystal',
    quantity: '450 мл',
    quantityImg:bottleImgUrl,
    barcode: '4604049097548',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '8,7',
    typeOfCare: 'уход за руками,уход за телом',
  },
  {
    imgUrl: image2Url,
    title: 'ARIEL',
    description: 'Автомат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник',
    quantity: '15X28.8 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097549',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '28,6',
    typeOfCare: 'уход за руками,уход за телом',
  },
  {
    imgUrl: image3Url,
    title: 'BIMAX',
    description: 'Порошок стиральный Автомат 100 пятен COMPACT',
    quantity: '1500 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097550',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
    typeOfCare: 'уход за телом'
  },
  {
    imgUrl: image1Url,
    title: 'AOS',
    description: 'средство для мытья посуды Crystal',
    quantity: '450 мл',
    quantityImg:bottleImgUrl,
    barcode: '4604049097551',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
    typeOfCare: 'уход за руками'
  },
  {
    imgUrl: image2Url,
    title: 'ARIEL',
    description: 'Автомат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник',
    quantity: '15X28.8 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097552',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
    typeOfCare: 'уход за руками,уход за телом',
  },
  {
    imgUrl: image3Url,
    title: 'BIMAX',
    description: 'Порошок стиральный Автомат 100 пятен COMPACT',
    quantity: '1500 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097553',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
    typeOfCare: 'уход за руками,уход за телом',
  },
  {
    imgUrl: image1Url,
    title: 'AOS',
    description: 'средство для мытья посуды Crystal',
    quantity: '450 мл',
    quantityImg:bottleImgUrl,
    barcode: '4604049097554',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
    typeOfCare: 'уход за руками',
  },
  {
    imgUrl: image2Url,
    title: 'ARIEL',
    description: 'Автомат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник',
    quantity: '15X28.8 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097555',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
    typeOfCare: 'уход за руками,уход за телом',
  },
  {
    imgUrl: image3Url,
    title: 'BIMAX',
    description: 'Порошок стиральный Автомат 100 пятен COMPACT',
    quantity: '1500 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097556',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
    typeOfCare: 'уход за телом',
  },
  {
    imgUrl: image1Url,
    title: 'AOS',
    description: 'средство для мытья посуды Crystal',
    quantity: '450 мл',
    quantityImg:bottleImgUrl,
    barcode: '4604049097557',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,76',
    typeOfCare: 'уход за руками,уход за телом',
  },
  {
    imgUrl: image2Url,
    title: 'ARIEL',
    description: 'Автомат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник',
    quantity: '15X28.8 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097558',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '49,76',
    typeOfCare: 'уход за руками,уход за телом',
  },
  {
    imgUrl: image3Url,
    title: 'BIMAX',
    description: 'Порошок стиральный Автомат 100 пятен COMPACT',
    quantity: '1500 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097559',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '53,76',
    typeOfCare: 'уход за руками',
  },
  {
    imgUrl: image1Url,
    title: 'AOS',
    description: 'средство для мытья посуды Crystal',
    quantity: '450 мл',
    quantityImg:bottleImgUrl,
    barcode: '4604049097560',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '78,76',
    typeOfCare: 'уход за руками',
  },
  {
    imgUrl: image2Url,
    title: 'ARIEL',
    description: 'Автомат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник',
    quantity: '15X28.8 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097561',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '65,76',
    typeOfCare: 'уход за руками',
  },
  {
    imgUrl: image3Url,
    title: 'BIMAX',
    description: 'Порошок стиральный Автомат 100 пятен COMPACT',
    quantity: '1500 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097562',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '122,76',
    typeOfCare: 'уход за телом',
  },
  {
    imgUrl: image1Url,
    title: 'AOS',
    description: 'средство для мытья посуды Crystal',
    quantity: '450 мл',
    quantityImg:bottleImgUrl,
    barcode: '4604049097563',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '18,76',
    typeOfCare: 'уход за телом',
  },
  {
    imgUrl: image2Url,
    title: 'ARIEL',
    description: 'Автомат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник',
    quantity: '15X28.8 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097564',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48',
    typeOfCare: 'уход за руками,уход за телом',
  },
  {
    imgUrl: image3Url,
    title: 'BIMAX',
    description: 'Порошок стиральный Автомат 100 пятен COMPACT',
    quantity: '1500 г',
    quantityImg:boxImgUrl,
    barcode: '4604049097565',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '48,7',
    typeOfCare: 'уход за руками',
  },
  {
    imgUrl: image1Url,
    title: 'AOS',
    description: 'средство для мытья посуды Crystal',
    quantity: '450 мл',
    quantityImg:bottleImgUrl,
    barcode: '4604049097566',
    manufacturer: 'Нэфис',
    brand: 'AOS',
    price: '43,79',
    typeOfCare: 'уход за руками,уход за телом',
  },
];

export default goodsData;
